spring:
  datasource:
    hikari:
      auto-commit: false
    url: jdbc:postgresql://localhost:5432/shops
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        to translate lang into sql
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

api:
  prefix: /api/v1
